/*----------------------------------------*\
  client-perpetuite-3 - ErrorDictionnary.js
  @author Evrard Vincent (vincent@ogre.be)
  @Date:   2022-07-22 14:50:06
  @Last Modified time: 2022-08-19 15:13:38
\*----------------------------------------*/
export default Object.freeze({
	unknown : `Unknown error : `,
	"(-1)" : "*Notyet implemented*",
	"(-2)" : "*Obsolete keyword*",
	"(-300)" : "*Illegal monitor command*",
	"(-301)" : "*No program specified*",
	"(-302)" : "*DO not primed*",
	"(-303)" : "*Controller not in automatic mode*",
	"(-304)" : "*Controller not in manual mode*",
	"(-305)" : "*Storage area format error*",
	"(-307)" : "*Program not executable*",
	"(-308)" : "*Program interlocked*",
	"(-309)" : "*Program already exists*",
	"(-310)" : "*Can't access protected or read-only program*",
	"(-311)" : "*Invalid when program task active*",
	"(-312)" : "*Can't start while program running*",
	"(-313)" : "*Can't go on, use EXECUTE or PRIME*",
	"(-314)" : "*Switch can't be enabled*",
	"(-315)" : "*Invalid software configuration*",
	"(-316)" : "*Software checksum error*",
	"(-317)" : "*Controller not in network mode*",
	"(-318)" : "*Program task not active*",
	"(-319)" : "*Program task not in use*",
	"(-350)" : "*Can't delete .PROGRAM statement*",
	"(-351)" : "*First statement must be .PROGRAM*",
	"(-352)" : "*Invalid in read-only mode*",
	"(-353)" : "*No other program referenced*",
	"(-354)" : "*Line too long*",
	"(-355)" : "*Can't exit while lines attached*",
	"(-356)" : "*Not found*",
	"(-357)" : "*Recursive macros illegal*",
	"(-358)" : "*Canceled*",
	"(-359)" : "*Illegal in debug monitor mode*",
	"(-360)" : "*Must be in debug mode*",
	"(-361)" : "*Can't change modes while task running*",
	"(-362)" : "*Can't execute from SEE program instruction*",
	"(-363)" : "*Unknown editor command*",
	"(-364)" : "*Can't create program in read-only mode*",
	"(-365)" : "*Illegal in read-write mode*",
	"(-366)" : "*Invalid when program on stack*",
	"(-380)" : "*Breakpoint not allowed here*",
	"(-400)" : "*Aborted*",
	"(-401)" : "*Undefined value*",
	"(-402)" : "*Illegal value*",
	"(-403)" : "*Illegal assignment*",
	"(-404)" : "*Illegal array index*",
	"(-405)" : "*Illegal digital signal*",
	"(-406)" : "*Undefined program or variable name*",
	"(-407)" : "*Invalid argument*",
	"(-408)" : "*Program argument mismatch*",
	"(-409)" : "*Arithmetic overflow*",
	"(-410)" : "*Negative square root*",
	"(-411)" : "*Not enough storage area*",
	"(-412)" : "*Branch to undefined label* Step nnn",
	"(-413)" : "*Not enough program stack space*",
	"(-414)" : "*Can't mix MC & program instructions*",
	"(-416)" : "*String variable overflow*",
	"(-417)" : "*String too short*",
	"(-418)" : "*Illegal memory reference*",
	"(-419)" : "*Illegal when command program active*",
	"(-420)" : "*Undefined value in this context*",
	"(-421)" : "*Program not on top of stack*",
	"(-422)" : "*Function already enabled*",
	"(-423)" : "*Illegal operation*",
	"(-424)" : "*Unknown keyword*",
	"(-425)" : "*Calibration program not loaded*",
	"(-426)" : "*Can't find calibration program file*",
	"(-450)" : "*Can't interpret line*",
	"(-451)" : "*Unexpected text at end of line*",
	"(-452)" : "*Unknown instruction*",
	"(-453)" : "*Ambiguous name*",
	"(-454)" : "*Missing argument*",
	"(-455)" : "*Invalid program or variable name*",
	"(-456)" : "*Invalid number format*",
	"(-457)" : "*Reserved word illegal*",
	"(-458)" : "*Illegal expression syntax*",
	"(-459)" : "*Missing parenthesis*",
	"(-460)" : "*Missing quote mark*",
	"(-461)" : "*Invalid format specifier*",
	"(-462)" : "*Unknown function*",
	"(-463)" : "*Invalid statement label*",
	"(-464)" : "*Duplicate statement label*",
	"(-465)" : "*Variable type mismatch*",
	"(-466)" : "*Illegal use of belt variable*",
	"(-467)" : "*Illegal .PROGRAM statement*",
	"(-468)" : "*Duplicate .PROGRAM arguments*",
	"(-469)" : "*Attempt to redefine variable type*: variable_name",
	"(-470)" : "*Attempt to redefine variable class*: variable_name",
	"(-471)" : "*Misplaced declaration statement*",
	"(-472)" : "*Control structure error* Step nnn",
	"(-473)" : "*Control structure error*",
	"(-474)" : "*Too many array indices*",
	"(-475)" : "*Missing bracket*",
	"(-476)" : "*Invalid qualifier*",
	"(-477)" : "*Ambiguous AUTO invalid*",
	"(-500)" : "*File already exists*",
	"(-501)" : "*Nonexistent file*",
	"(-502)" : "*Illegal I/O device command*",
	"(-503)" : "*Device full*",
	"(-504)" : "*Unexpected end of file*",
	"(-506)" : "*File already open*",
	"(-507)" : "*I/O communication error*",
	"(-508)" : "*Device not ready*",
	"(-509)" : "*Directory error*",
	"(-510)" : "*Data checksum error*",
	"(-511)" : "*Input block error*",
	"(-512)" : "*File format error*",
	"(-513)" : "*File not opened*",
	"(-514)" : "*File or subdirectory name error*",
	"(-515)" : "*Already attached to logical unit*",
	"(-516)" : "*Not attached to logical unit*",
	"(-517)" : "*I/O queue full*",
	"(-518)" : "*Illegal I/O channel number*",
	"(-519)" : "*Driver internal consistency error*",
	"(-520)" : "*Invalid disk format*",
	"(-521)" : "*Wrong disk loaded*",
	"(-522)" : "*Data error on device*",
	"(-523)" : "*Bad block in disk header*",
	"(-524)" : "*Communications overrun*",
	"(-525)" : "*Illegal I/O redirection specified*",
	"(-526)" : "*No data received*",
	"(-527)" : "*Illegal user LUN specified*",
	"(-528)" : "*Illegal record length*",
	"(-529)" : "*Output record too long*",
	"(-530)" : "*Protection error*",
	"(-531)" : "*Communication time-out*",
	"(-532)" : "*Out of I/O buffer space*",
	"(-533)" : "*Invalid hardware configuration*",
	"(-534)" : "*Network restarted remotely*",
	"(-535)" : "*Network closed locally*",
	"(-536)" : "*Too many network errors*",
	"(-537)" : "*Unknown network node*",
	"(-538)" : "*Network node off line*",
	"(-539)" : "*No matching connection*",
	"(-540)" : "*Invalid connection specified*",
	"(-541)" : "*Invalid network protocol*",
	"(-542)" : "*Network not enabled*",
	"(-543)" : "*Illegal when network enabled*",
	"(-544)" : "*Not configured as accessed*",
	"(-545)" : "*Nonexistent subdirectory*",
	"(-546)" : "*Subdirectory list too long*",
	"(-547)" : "*Subdirectory in use*",
	"(-548)" : "*Illegal while protocol active*",
	"(-549)" : "*Out of graphics memory*",
	"(-550)" : "*Too many windows*",
	"(-551)" : "*Font not loaded*",
	"(-552)" : "*Graphics processor timeout*",
	"(-553)" : "*Too many arguments*",
	"(-554)" : "*Too many closeable windows*",
	"(-555)" : "*Graphics storage area format error*",
	"(-557)" : "*Can't create new slide bar*",
	"(-558)" : "*Graphics software checksum error*",
	"(-559)" : "*Out of network resources*",
	"(-560)" : "*Invalid network resource*",
	"(-561)" : "*Invalid network address*",
	"(-562)" : "*Network timeout*",
	"(-563)" : "*Remote has not exported network resource*",
	"(-564)" : "*Network resource name conflict*",
	"(-565)" : "*Network connection terminated*",
	"(-566)" : "*Not owner*",
	"(-567)" : "*Not a directory*",
	"(-568)" : "*Is a directory*",
	"(-569)" : "*File too large*",
	"(-570)" : "*File name too long*",
	"(-571)" : "*Directory not empty*",
	"(-587)" : "*Network resource already in use*",
	"(-600)" : "*Stopped due to servoing error*",
	"(-601)" : "*Robot not attached to this program*",
	"(-602)" : "*Robot already attached to program*",
	"(-603)" : "*COMP mode disabled*",
	"(-604)" : "*Robot power off*",
	"(-605)" : "*Robot not calibrated*",
	"(-606)" : "*Robot overheated*",
	"(-607)" : "*No air pressure*",
	"(-608)" : "*External E-STOP 1 detected by CPU*",
	"(-609)" : "*Illegal joint number*",
	"(-610)" : "*Location out of range*",
	"(-611)" : "*Must use straight-line motion*",
	"(-612)" : "*Straight-line motion can't alter configuration*",
	"(-613)" : "*Illegal motion from here*",
	"(-614)" : "*Attempt to modify active belt*",
	"(-615)" : "*Belt not enabled*",
	"(-616)" : "*Belt window violation*",
	"(-617)" : "*Belt servo dead*",
	"(-618)" : "*Location too close*",
	"(-619)" : "*Invalid orientation*",
	"(-620)" : "*Speed pot or STEP not pressed*",
	"(-621)" : "*Robot interlocked*",
	"(-622)" : "*No robot connected to system*",
	"(-623)" : "*Stop-on-force triggered*",
	"(-624)" : "*Force protect limit exceeded*",
	"(-625)" : "*Invalid servo initialization data*",
	"(-626)" : "*Can't ALTER and track belt*",
	"(-627)" : "*Robot power on*",
	"(-628)" : "*Robot module not loaded* ID:n",
	"(-629)" : "*SYSFAIL detected by CPU*",
	"(-630)" : "*Backplane E-STOP detected by CPU*",
	"(-632)" : "*Power failure detected by robot*",
	"(-633)" : "*PANIC command*",
	"(-635)" : "*Cartesian control of robot not possible*",
	"(-636)" : "*Trajectory clock overrun*",
	"(-637)" : "*Illegal while joints SPIN'ing*",
	"(-638)" : "*SPIN motion not permitted*",
	"(-639)" : "*Manual brake release*",
	"(-640)" : "*E-STOP from robot*",
	"(-641)" : "*E-STOP from amplifier*",
	"(-642)" : "*SYSFAIL detected by robot*",
	"(-643)" : "*E-STOP detected by robot*",
	"(-644)" : "*Incompatible safety configuration*",
	"(-645)" : "*Power disabled: Manual/Auto changed*",
	"(-646)" : "*HIGH POWER button not pressed*",
	"(-647)" : "*Collision avoidance dead-lock*",
	"(-648)" : "*Safety system not commissioned*",
	"(-649)" : "*Timeout: MCP enable switch not toggled*",
	"(-650)" : "*Manual control pendant failure*",
	"(-651)" : "*RSC communications failure*",
	"(-652)" : "*RSC reset*",
	"(-653)" : "*RSC time-out*",
	"(-654)" : "*RSC transmission garbled*",
	"(-655)" : "*RSC bad packet format*",
	"(-656)" : "*RSC calibration load failure*",
	"(-657)" : "*Pendant Not Connected*",
	"(-658)" : "*Device hardware not present*",
	"(-659)" : "*Device time-out*",
	"(-660)" : "*Device error*",
	"(-661)" : "*NVRAM data invalid*",
	"(-662)" : "*Device sensor error*",
	"(-663)" : "*Device reset*",
	"(-665)" : "*NVRAM battery failure*",
	"(-666)" : "*Must use CPU #1*",
	"(-667)" : "*Power failure detected*",
	"(-668)" : "*Device in use*",
	"(-669)" : "*RSC hardware failure*",
	"(-670)" : "*RSC power failure*",
	"(-671)" : "*Servo board 12V fuse open*",
	"(-672)" : "*Servo board solenoid fuse open*",
	"(-673)" : "*Servo board E-Stop fuse open*",
	"(-674)" : "*Servo task overloaded*",
	"(-675)" : "*Timeout enabling power*",
	"(-676)" : "*RSC module ID doesn't match robot*",
	"(-677)" : "*Servo protocol incompatible*",
	"(-678)" : "*Duplicate servo node ID*",
	"(-679)" : "*Expected servo node not found*",
	"(-680)" : "*Servo node not downloaded*",
	"(-701)" : "*VISION not enabled*",
	"(-702)" : "*No prototypes*",
	"(-703)" : "*Too many vision requests pending*",
	"(-704)" : "*No objects seen*",
	"(-705)" : "*Camera not running*",
	"(-706)" : "*Invalid request while camera running*",
	"(-707)" : "*Unknown prototype*",
	"(-710)" : "*Camera disconnected*",
	"(-712)" : "*Maximum number of prototypes exceeded*",
	"(-713)" : "*Vision not calibrated*",
	"(-714)" : "*Camera already running*",
	"(-717)" : "*Not enough prototype storage area*",
	"(-718)" : "*Duplicate prototype name*",
	"(-719)" : "*Camera already off*",
	"(-720)" : "*Vision option not installed*",
	"(-721)" : "*Bad grip definition*",
	"(-722)" : "*Camera interface board absent*",
	"(-723)" : "*No picture data available*",
	"(-724)" : "*Illegal display mode*",
	"(-726)" : "*Bad camera calibration*",
	"(-727)" : "*Invalid vision X/Y ratio*",
	"(-728)" : "*Image processing board failure*",
	"(-729)" : "*Invalid request while vision training*",
	"(-730)" : "*Information not available*",
	"(-731)" : "*Unknown sub-prototype*",
	"(-732)" : "*Invalid model name*",
	"(-733)" : "*Vision system out of memory*",
	"(-734)" : "*Can't open vision window for read/write*",
	"(-735)" : "*Invalid vision argument*",
	"(-736)" : "*Font not defined*",
	"(-737)" : "*Font already defined*",
	"(-738)" : "*Font not completely trained*",
	"(-739)" : "*Maximum number of samples trained*",
	"(-740)" : "*Duplicate character in font*",
	"(-741)" : "*Invalid character in font*",
	"(-742)" : "*Character not in font*",
	"(-743)" : "*Region too big*",
	"(-744)" : "*Region too complicated*",
	"(-745)" : "*Expected character(s) not found*",
	"(-746)" : "*Template of uniform intensity*",
	"(-747)" : "*Template not defined*",
	"(-748)" : "*Template already defined*",
	"(-749)" : "*Vision aborted*",
	"(-750)" : "*Mixing half and full resolutions*",
	"(-751)" : "*No vision system selected*",
	"(-752)" : "*AOI not defined*",
	"(-753)" : "*Out of vision transform memory*",
	"(-754)" : "*Correlation template too big*",
	"(-755)" : "*Data overflow*",
	"(-756)" : "*A scratch frame store is needed (use VSELECT)*",
	"(-757)" : "*Inconsistent hierarchy levels*",
	"(-758)" : "*No models*",
	"(-759)" : "*Unknown model*",
	"(-760)" : "*Duplicate model*",
	"(-761)" : "*No models planned*",
	"(-762)" : "*Vision software incompatible*",
	"(-763)" : "*Inconsistent model mode setting*",
	"(-764)" : "*Not supported in simulated vision mode*",
	"(-765)" : "*[Fatal] Vision processor failure*",
	"(-766)" : "*Vision hardware/software mismatch*",
	"(-767)" : "*Vision internal error*",
	"(-768)" : "*Vision operation timeout*",
	"(-800)" : "*Unknown error code*",
	"(-801)" : "*Invalid VFEATURE access*",
	"(-802)" : "*Invalid camera calibration*",
	"(-803)" : "*Illegal camera number*",
	"(-804)" : "*Option not installed*",
	"(-805)" : "*Hardware not in system*",
	"(-859)" : "*Database manager internal error*",
	"(-900)" : "*Robot module not enabled*",
	"(-901)" : "*Obstacle collision detected*",
	"(-902)" : "*Interrupted multi-segment motion*",
	"(-903)" : "*DeviceNet: Critical device off-line*",
	"(-904)" : "*[Fatal] E-STOP signals are stuck off*",
	"(-905)" : "*[Fatal] I/O processor failure*",
	"(-906)" : "*Robot power off requested*",
	"(-907)" : "*E-STOP circuit relay failure*",
	"(-908)" : "*E-STOP from front panel button*",
	"(-909)" : "*E-STOP from MCP E-STOP button*",
	"(-910)" : "*E-STOP from user E-STOP button*",
	"(-911)" : "*E-STOP from front panel external input*",
	"(-912)" : "*E-STOP from user enable switch*",
	"(-913)" : "*E-STOP from MCP enable switch*",
	"(-914)" : "*E-STOP 2 detected by CPU*",
	"(-915)" : "*MCP enable switch 1 off detected by CPU*",
	"(-916)" : "*MCP enable switch 2 off detected by CPU*",
	"(-917)" : "*Manual mode switch 1 off detected by CPU*",
	"(-918)" : "*Manual mode switch 2 off detected by CPU*",
	"(-919)" : "*E-STOP asserted by CPU*",
	"(-920)" : "*[Fatal] Manual mode switch stuck off*",
	"(-921)" : "*E-STOP from user muted safety gate*",
	"(-922)" : "*E-STOP channels 1 and 2 do not match*",
	"(-923)" : "*E-STOP circuit is shorted*",
	"(-924)" : "*Front panel HIGH POWER lamp failure*",
	"(-925)" : "*Front panel serial bus failure*",
	"(-927)" : "*1394 communications timeout*",
	"(-929)" : "*E-Stop from Line E-Stop input*",
	"(-931)" : "*Servo hardware failure*",
	"(-932)" : "*Manual mode cannot be enabled*",
	"(-935)" : "*Orientation out of range*",
	"(-936)" : "*Kinematic solution not found*",
	"(-939)" : "*E-Stop unstable*",
	"(-999)" : "*Aborted*",
	"(-1001)" : "*Invalid servo error* Mtr n",
	"(-1002)" : "*Position out of range* Jt",
	"(-1003)" : "*Time-out nulling errors* Mtr n",
	"(-1004)" : "*No zero index* Mtr n",
	"(-1005)" : "*Unexpected zero index* Mtr n",
	"(-1006)" : "*Soft envelope error* Mtr n",
	"(-1007)" : "*Motor stalled* Mtr n",
	"(-1008)" : "*Encoder quadrature error* Mtr n",
	"(-1009)" : "*Timeout enabling amplifier* Mtr n",
	"(-1010)" : "*Invalid error code* Belt n",
	"(-1011)" : "*No zero index* Belt n",
	"(-1012)" : "*Unexpected zero index* Belt n",
	"(-1013)" : "*Encoder quadrature error* Belt n",
	"(-1014)" : "*[Fatal] Initialization failure* Mtr n",
	"(-1015)" : "*Initialization failure* Belt n",
	"(-1016)" : "*Motor overheating* Mtr n",
	"(-1018)" : "*Motor amplifier fault* Mtr n",
	"(-1021)" : "*Duty-cycle exceeded* Mtr n",
	"(-1022)" : "*Skew envelope error* Mtr n",
	"(-1023)" : "*Position out of range* Mtr n",
	"(-1025)" : "*Encoder fault* Mtr n",
	"(-1026)" : "*Software incompatible* Code n",
	"(-1027)" : "*Hard envelope error* Mtr n",
	"(-1028)" : "*Soft overspeed error* Mtr n",
	"(-1029)" : "*Negative overtravel* Mtr n",
	"(-1033)" : "*Positive overtravel* Mtr n",
	"(-1034)" : "*Overtravel* Mtr n",
	"(-1035)" : "*Safety speed limit error* Chn nn",
	"(-1101)" : "*[Fatal] Servo process dead* CPU n",
	"(-1102)" : "*[Fatal] Servo code incompatible* CPU n",
	"(-1104)" : "*[Fatal] Servo dead* Mtr n",
	"(-1105)" : "*Motor startup failure* Mtr n",
	"(-1106)" : "*Calibration sensor failure* Mtr n",
	"(-1107)" : "*[Fatal] Servo init failure* CPU n",
	"(-1108)" : "*Safety system init failure* Code n",
	"(-1109)" : "*Safety system fault* Code n",
	"(-1110)" : "*Unexpected PSS state* Code nnn",
	"(-1111)" : "*E-STOP from safety system* Code n",
	"(-1112)" : "*Remote digital input failed* Block N",
	"(-1113)" : "*Remote digital output failed* Block N",
	"(-1115)" : "*Robot power system failure* Code n"
});